version: '3' 

services: 
  myredis: 
    image: 'redis:alpine' 
  mypostgres: 
    image: 'postgres:alpine' 
    environment: 
      - POSTGRES_PASSWORD=1qaz2wsx 
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres 
    volumes: 
      - /Users/michalpodgorni/Docker/postgresdata:/var/lib/postgresql/data 
  mybackend: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./mybackend
    volumes: 
      - /opt/app/node_modules 
      - /Users/michalpodgorni/DevOps/dockers/mybackend:/opt/app 
    environment: 
      - POSTGRES_PASSWORD=1qaz2wsx 
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres 
      - REDIS_HOST=myredis 
      - POSTGRES_HOST=mypostgres 
    ports: 
      - '5000:4000' #{local}:{server}
  mynginx: 
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./mynginx
    ports: 
      - '9090:80'
  myfrontend:
    build:
      dockerfile: Dockerfile
      context: ./myfrontend
    volumes:
      - /opt/app/node_modules
      - ./myfrontend:/opt/app