apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackend-deployment
  labels:
    component: backend
    app: myapp

spec:
  template:
    metadata:
      name: mybackend-pod
      labels:
        component: backend
        app: myapp
    spec:
      containers:
        - name: mybackend-container
          image: devipod/mybackend
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGHOST
            - name: PGDATABASE
              valueFrom: 
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom: 
                configMapKeyRef:
                  name: mypostgres-config
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mypostgres-secret
                  key: PGPASSWORD
            - name: REDIS_HOST
              value: myredis-clusterip
            - name: REDIS_PORT
              value: '6379'
  replicas: 3
  selector: 
    matchLabels: 
      app: myapp
      component: backend