apiVersion: v1
kind: Pod
metadata: 
  name: mynginx-pod
  labels: 
    component: web
    app: my-app

spec: 
  containers: 
    - name: mynginx
      image: nginx:alpine
      ports: 
        - containerPort: 80